name: PR gatekeeper
on:
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    checks:
        runs-on: ubuntu-latest
        steps:
            - name: Print Target branch
              run: echo "Target branch is ${{ github.event.pull_request.base.ref }}"
            - name: Print PR number
              run: echo "PR number is ${{ github.event.pull_request.number }}"
            - name: finish checks
              run: echo "Gatekeeper checks finished successfully"